# Site Info
title: YW & YY
tagline: "YW & YY's blog"
description: "YW & YY's blog powered by jekyll theme"
baseurl: ""
url: https://greeksharifa.github.io
logo: '/public/img/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: YW & YY
  description: <strong>Developer and Analyst</strong>, YW & YY.
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    # linkedin:  <hide>
    github:    https://github.com/greeksharifa
    # facebook:  <hide>
    # twitter:   <hide> https://twitter.com/Li_Zhihao
    # weibo:     <hide> http://weibo.com/41173780
    email:     mailto:sharifa@snu.ac.kr

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Github Project:
    - 'http://greeksharifa.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/Andre_Derain_Fishing_Boats_Collioure.jpg
  caption: Andre Derain, Fishing Boats Collioure, 1905. France.

# Plugins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'greeksharifa-github-io' # leave blank if you don't want disqus

