# Site Info
title: YW & YY
tagline: "세상의 변화에 대해 관심이 많은 이들의 Tech Blog"
description: "YW & YY's ML blog powered by jekyll theme"
baseurl: ""
url: https://greeksharifa.github.io
logo: '/public/img/logo.webp'

# Site configurations
gems:
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'base16.solarized'
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
# permalink: /:title/

version: 1.0.0

# About/contact
author:
  name: YW & YY
  description: <strong>AI Researcher & Data Scientist</strong>, YW & YY.
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    # linkedin:  <hide>
    github:    https://github.com/greeksharifa
    # facebook:  <hide>
    # twitter:   <hide> https://twitter.com/Li_Zhihao
    # weibo:     <hide> http://weibo.com/41173780
    email:     mailto:greeksharifa@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Github Project:
    - 'https://github.com/greeksharifa/greeksharifa.github.io'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/Andre_Derain_Fishing_Boats_Collioure.jpg
  caption: Andre Derain, Fishing Boats Collioure, 1905. France.

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Plugins
mathjax: true # whether support mathjax
google_analytics_token: 'G-XEE6P4YHK9' # leave blank if you don't want google analytics
disqus_short_name: 'greeksharifa-github-io' # leave blank if you don't want disqus

comments:
  provider    : "disqus"                                # comment 처리 사이트 명칭 기재
              # false (default), "disqus", "discourse", "facebook"
              # "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname : "greeksharifa-github-io"                    # disqus의 shortname 기재

# Analytics
analytics:
  provider               : "google-universal" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-XEE6P4YHK9"
    anonymize_ip         : # true, false (default)